[providers]
    [providers.docker]
        exposedByDefault = false

[entryPoints]
    [entryPoints.http]
        address = ":80"
    [entryPoints.https]
        address = ":443"

[certificatesResolvers]
    [certificatesResolvers.letsencrypt]
        [certificatesResolvers.letsencrypt.acme]
            email = "josdanind@proton.me"
            storage= "/certificates/acme.json"
            [certificatesResolvers.myresolver.acme.tlsChallenge]
